# Exported from Render on 2025-06-26
services:
  - type: web
    name: bloodbankmanagement
    runtime: python
    pythonVersion: 3.10.13
    repo: https://github.com/vandana1980/bloodbankmanagement-master
    plan: free
    envVars:
      - key: Bloodbank
        sync: false
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bloodbankmanagement.wsgi:application
    autoDeployTrigger: commit
version: "1"
