# Updated render.yaml
services:
  - type: web
    name: bloodbankmanagement
    runtime: python
    pythonVersion: 3.10.13  # 👈 ADD THIS LINE
    repo: https://github.com/vandana1980/bloodbankmanagement-master
    plan: free
    envVars:
      - key: Bloodbank
        sync: false
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bloodbankmanagement.wsgi:application  # 👈 FIX THIS LINE
    autoDeployTrigger: commit
version: "1"
