# Exported from Render on 2025-06-26T05:04:54Z
services:
- type: web
  name: bloodbankmanagement
  runtime: python
  repo: https://github.com/vandana1980/bloodbankmanagement-master
  plan: free
  envVars:
  - key: Bloodbank
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn bloodbankmanagement
  autoDeployTrigger: commit
version: "1"
